version: "3"

services:
  # Database config
  mysql:
    image: mysql:8.0.33-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ushorter
      MYSQL_ROOT_PASSWORD: BHU*nji9
    volumes:
      - mysql_data:/var/lib/mysql
  
  # Reddis config
  redis: 
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
      
  # uShorter config   
  app:
    image: ushorter:latest
    container_name: ushorter
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ushorter?autoReconnect=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: BHU*nji9
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

volumes:
  mysql_data:

